apiVersion: apps/v1
kind: Deployment
metadata:
  name: cli-orderer0-deployment
  labels: {
    component: orderer0,
    type: cli,
    org: orderer
  }
spec:
  replicas: 1
  selector:
    matchLabels:
      component: orderer0
      type: cli
      org: orderer
  template:
    metadata:
      labels:
        component: orderer0
        type: cli
        org: orderer
    spec:
      volumes:
        - name: my-pv-storage
          persistentVolumeClaim:
            claimName: my-pv-claim
      containers:
        - name: orderer0-orderer
          image: hyperledger/fabric-tools:2.2.1
          workingDir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
          command: ["sleep"]
          args: ["infinity"]
          env:
            - name: GOPATH
              value: /opt/gopath
            - name: CORE_PEER_ADDRESSAUTODETECT
              value: "true"
            - name: CORE_PEER_ID
              value: cli-orderer0-orderer
            - name: CORE_PEER_ADDRESS
              value: orderer0-service:7050
            - name: CORE_PEER_LOCALMSPID
              value: orderer
            - name: CORE_PEER_MSPCONFIGPATH
              value: /var/hyperledger/orderer/msp
          volumeMounts:
            - mountPath: /var/hyperledger/orderer/msp
              name: my-pv-storage
              subPath: files/crypto-config/ordererOrganizations/orderer/orderers/orderer0/msp
            - mountPath: /var/hyperledger/orderer/tls
              name: my-pv-storage
              subPath: files/crypto-config/ordererOrganizations/orderer/orderers/orderer0/tls
            - mountPath: /var/hyperledger/orderer/data
              name: my-pv-storage
              subPath: files/orderer
